# Generated by Django 4.1.4 on 2023-09-15 14:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
